name: C++ CI for hello world

on:
  push:
    branches: [project]  # limit to main branch

jobs:
  build-and-test-helloworld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: install libs
        run: sudo apt-get install gcc-multilib g++-multilib libc6-dev-i386
      - name: make
        run: make